# Generated by Django 5.1.1 on 2024-09-25 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course name')),
                ('pic', models.TextField(default='', verbose_name='Course picture')),
                ('description', models.TextField(null=True, verbose_name='Course Description')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Lesson title')),
                ('description', models.TextField(default='', verbose_name='Lesson description')),
                ('in_course_id', models.IntegerField(default='0', verbose_name='In course ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course')),
            ],
        ),
    ]
