# Generated by Django 5.1.1 on 2024-09-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('in_course_id', 'course'), 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterField(
            model_name='course',
            name='pic',
            field=models.URLField(blank=True, verbose_name='Course picture'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'in_course_id')},
        ),
    ]
