# Generated by Django 5.1.1 on 2024-09-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('course', 'in_course_id'), 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
    ]
